# Site settings
title: ProximiTreats | Blijf op de hoogte van uw favoriete mobiele verkopers!
email:
description: Een landingspagina voor de ProximiTreats mobiele app, waarmee gebruikers op de hoogte blijven van hun favoriete mobiele verkopers.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://proximitreats.com" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: 
addthis_id: 
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  # - title: twitter
  #   url: https://twitter.com/lantoniotrento
  # - title: facebook
  #   url: https://facebook.com/lantoniotrento
  # - title: google-plus
  #   url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
# paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","vendor","bundle"]
include:
  - .well-known
  - CNAME

plugins: [jekyll-paginate, jekyll-feed]
# Build settings
